from langchain.agents import create_agent
from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from typing import List
from langchain_tavily import TavilySearch   

load_dotenv()  # Load environment variables from a .env file if present

class SearchSource(BaseModel):
    """Schema for source used in search agent"""
    url: str = Field(description="The URL of the source.")
    
class AgentResponse(BaseModel):
    """Schema for agent response with answer and sources"""
    answer: str = Field(description="The final response generated by the agent")
    sources: List[SearchSource] = Field(default_factory=List, description="The list of sources used by the agent to generate the answer.")

search = TavilySearch()

# Built up agent with Groq model and search tool
model = ChatGroq(model="llama-3.3-70b-versatile", temperature=1)
tools = [search]
agent = create_agent(model=model, tools=tools, response_format=AgentResponse)


def main():
    print("Hello from langchain-course!")
    result = agent.invoke({"messages": HumanMessage(content="Search for job postings for AI Engineer on LinkedIn in Toronto, and list job postings and link resources")})
    print("Agent Result:", result)
    


if __name__ == "__main__":
    main()
