from typing import List

from pydantic import BaseModel, Field


class Source(BaseModel):
    """schema for a single source"""

    url: str = Field(description="The URL of the source")


class AgentResponse(BaseModel):
    """schema for the agent response with answer and sources"""

    answer: str = Field(description="The final answer generated by the agent")
    sources: List[Source] = Field(
        description="List of sources used to generate the answer"
    )
